### ISSUE TITLE
请问效果咋样呢？

### ISSUE THREAD

**Issue by HandsLing** [yw0nam/Adaspeech#1]
请问您复现的这个效果咋样呢，可以实现声音个性化定制吗，支持一个人输入一两百条语音就能够复刻出来

**Comment by yw0nam** [comment]
Sorry,  but, i don't understand chinese. 
If you don't mind, can you use english?

**Comment by HandsLing** [comment]
sorry for the chinese
May I ask how you reproduced this project?  Can the voice be customized? It can be reproduced by inputting one or two hundred voices by one person.
and can you release your pretrained model? Thx

**Comment by yw0nam** [comment]
Sorry, currently, i'm not planning to release adaptation code.
and, i upload the pretrained model using LJspeech and Kokoro dataset.

**Comment by HandsLing** [comment]
You mean that this code cannot custom voice?
so what the difference be this code and FastSpeech2?
and where is the  pretrained model using LJspeech and Kokoro dataset?

**Comment by yw0nam** [comment]
My focus was to improve FastSpeech 2 acoustic generalization using Utterance level encoder and Phoneme level encoder rather than adaptation. So, adaptation was not my focus.

And, you can find pretrained network [here](https://drive.google.com/drive/folders/1m5bq9vkQV1VKq8QmuYoCpaf_WCk3cmWc), this is same link in readme.md

**Comment by HandsLing** [comment]
could you please share your log file? i want to know after your training, the value of your loss

**Comment by HandsLing** [comment]
and i want train a mandarin model ,  what should i change except symbols?

**Comment by yw0nam** [comment]
1. Give me your email address. Then, i will send you LJspeech training log file.
2. You need to change __init__.py, symbols.py and cleaners.py in text folder. My code is based on ming's code that support mandarin. Checking this [codes](https://github.com/ming024/FastSpeech2/tree/master/text) might help.
3. You need to make preprocessing step yourself, check preprocessor folder's ljspeech.py or other .py files

**Comment by HandsLing** [comment]
lck1994@foxmail.com
thank you very much
